language: c

# allow containerized build
sudo: false 

# Build deps
addons:
  apt:
    packages:
    - rpm
    - devscripts
    - debhelper

# before build script, run autoreconf
before_script: ./autogen.sh

# Default is "./configure && make && make test", but no tests yet
script:   
  - "curl -sL -o /tmp/zabbix-3.0.0.tar.gz http://sourceforge.net/projects/zabbix/files/ZABBIX%20Latest%20Stable/3.0.0/zabbix-3.0.0.tar.gz"
  - "tar -xzC /tmp -f /tmp/zabbix-3.0.0.tar.gz"
  - "./configure --with-zabbix=/tmp/zabbix-3.0.0/include && make"
